apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-config
  labels:
    resource: prometheus
spec:
  route:
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "webhook"
    routes:
      - match: 
          severity: warning
        receiver: webhook
  receivers:
    - name: "webhook"
      webhookConfigs:
        - url: "http://any_example_com/"
