apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    job: node-api
    app: sample-node-app
  namespace: node-app
spec:
  type: LoadBalancer
  selector:
    app: sample-node-app
  ports:
    - name: web
      port: 80
      targetPort: 8000  
